name: CI checks for DNA Tags

on:
  pull_request:
    branches:
      - main
jobs:
  run_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: pip install -r ./dev-requirements.txt
      - name: Install Package
        run: pip install .
      - name: Lint
        run: python -m invoke lint
      - name: Format
        run: python -m invoke format
      - name: Test
        run: python -m invoke test
